### ISSUE TITLE
Ad units set to display: none until window resize

### ISSUE THREAD

**Issue by johnpuddephatt** [oomphinc/wp-dfp#4]
Had DFP working fine without this plugin, but was interested in using it to make ad management a bit easier – first impressions are that this will definitely help do that!

Only problem I've got is that ad units are all stuck with  `style="display: none"` set on them on page load, which is only removed if the window is resized. This is happening regardless of the viewport size on page load. After resizing the window everything works as expected.

Occurring on Safari/Chrome/Firefox on OS X with all browser extensions (including ad blockers) disabled.

I've had a poke around in wp-dfp.js, and it seems that when wpdfp.init is being called on `$(document).ready` it isn't having the expected effect, but if I use setTimeout to add a delay of 500ms or more before wpdfp.init is called, then everything works as expected.

Relying on an arbitrary setTimeout isn't ideal, so any pointers would be gratefully received!

**Comment by jcowher** [comment]
Hi @johnpuddephatt,

Thanks for bringing this to our attention! I just created a patch in the [1.1.5 branch](https://github.com/oomphinc/wp-dfp/tree/1.1.5). Let me know if that fixes things for you.

**Comment by johnpuddephatt** [comment]
Yep, that seems to have sorted it! :+1:
