### ISSUE TITLE
Firefox defaulting to smallest sized ad size

### ISSUE THREAD

**Issue by duro** [oomphinc/wp-dfp#7]
I have this plugin setup utilizing the multiple break point ad sizes. This is working perfectly for me in Chrome, but on Firefox, it always shows the smallest ad size.

Here is a page where this is implemented and demonstrates the problem:

http://events.yoga/

I have tracked this down to something in the wp-dfp.js file, but due to it's minification, and the source maps behaving funny, I'm having trouble tracking it down precisely.

It seems that however the `sizeMapping` var on firefox is not gettting calculated properly in this block:

```
$ads.dfp( {
    dfpID:               wpdfp.network,
    collapseEmptyDivs:   false,
    setUrlTargeting:     false,
    setTargeting:        wpdfp.targeting,
    sizeMapping:         sizeMapping,
    afterEachAdLoaded:   wpdfp.afterEachAdLoaded,
    enableSingleRequest: true
} );
```

Any ideas?

Here is what I am seeing in Chrome:

https://www.evernote.com/l/AAUepWrVv9BIjpuqu7bnmvM18PXa8M2Z4Mw

And here is what I am seeing in FF:

https://www.evernote.com/l/AAWHZugrNLNCC6SIzqz3fc1AVdVNU6B2LY4

**Comment by jcowher** [comment]
Hi @duro,

Ok - this one is interesting! It looks like `jQuery.each()` is handled differently between Chrome and Firefox. Chrome gives the correct ordering of the slot sizes that are defined (smallest to largest), but Firefox is iterating starting largest to smallest - hence why you're always getting the smallest ad size in Firefox! I'll post a code update soon that fixes this. Just wanted to keep you posted.

**Comment by jcowher** [comment]
Committed 1.1.7... that should fix this!

**Comment by duro** [comment]
This worked great. Thanks!
